turkce ={"t1":"Milis Kurulum Aracı",
"t2":"Geri",
"t3":"İleri",
"t4":"""	Milis Linux (Milli İşletim Sistemi) sıfır kaynak koddan üretilen, kendine has paket yöneticisine sahip, bağımsız tabanlı yerli linux işletim sistemi projesidir. Genel felsefe olarak ülkemizdeki bilgisayar kullanıcıları için linuxu kolaylaştırıp Milis İşletim Sisteminin sorunsuz bir işletim sistemi olmasını sağlamayı ve yazılımsal olarak dışa bağımlı olmaktan kurtarmayı esas alır. Ayrıca her türlü katkıda bulunmak isteyenler için bulunmaz bir Türkçe açık kaynak projesidir.""",
"t5":"Belgeler",
"t6":"Forum",
"t7":"Git",
"t8":"İletişim",
"t9":"Dil seçiniz",
"t10":"Milis Linux Kurulumuna Hoşgeldiniz",
"t11":"Klavye Ayarları",
"t12":"Model",
"t13":"Ülke",
"t14":"Tür",
"t15":"Konum Ayarları",
"t16":"Bölge",
"t17":"Şehir",
"t18":"Kullanıcı Ayarları",
"t19":"Kullanıcı Adı",
"t20":"Giriş Adı",
"t21":"Bilgisayar Adı",
"t22":"En az 3 karakterden oluşmalı",
"t23":"En az 4 karakter ve harflerden oluşmalı",
"t24":"Kullanıcı Şifresi",
"t25":"En az 6 karakterden oluşmalı ve şifreler aynı olmalı",
"t26":"Şifre istemeden otomatik giriş yap",
"t27":"Yönetici hesabı için aynı şifreyi kullan",
"t28":"Yönetici Şifresi",
"t29":"Disk Ayarları",
"t30":"<b>1-Sistem bölümü:</b> Milis'in sistem dosyalarını kopyalacağı bölümdür. Ext4 biçiminde biçimlenir. <u>ZORUNLU</u>\n<b>2-Takas bölümü:</b> Milis ram sıkıntısı yaşadığında dosyaları geçici olarak kopyalamak için bir disk bölümüne ihtiyaç duyar. Bilgisayarınızın Ram miktarı düşükse takas bölümü oluşturunuz. <u>İSTEĞE BAĞLI</u>\n<b>3-UEFI bölümü:</b> Eğer UEFI'li bir BIOS'a sahipseniz ve UEFI kullanmak istiyorsanız diskte bir EFI alanına ihtiyacınız var. Varolan bir işletim sisteminiz ve kullandığı EFI alanı varsa lütfen o alanı seçiniz. Diskinizde başka işletim sistemi yoksa ve UEFI kullanmak istiyorsanız lütfen bir EFI alanı oluşturunuz. <u>İSTEĞE BAĞLI</u>",
"t31":"Diskler",
"t32":"Yenile",
"t33":"Sistem Bölümü",
"t34":"Takas Bölümü",
"t35":"UEFI Bölümü",
"t36":"Düzenle",
"t37":"Grub ön yükleyiciyi kur",
"t38":"Grub ön yükleyiciyi kurma",
"t39":"Kurulum Bilgisi",
"t40":"Sistem Dili",
"t41":"Klavye Modeli",
"t42":"Klavye Düzeni",
"t43":"Klavte Varyantı",
"t44":"Konum",
"t45":"Devam etmeniz halide seçmiş olduğunuz diske Milis Linux kurulacaktır",
"t46":"Devam et",
"t47":"Vazgeç",
"t48":"Milis Linux Kuruluyor",
"t49":"Diskler Sistemden Ayırılıyor",
"t50":"Sistem Diski Bağlanıyor",
"t51":"Chroot Oluşturuluyor",
"t52":"Dosyalar Kopyalama İçin Hesaplanıyor",
"t53":"Kopyalanıyor",
"t54":"Fstab oluşturuluyor",
"t55":"Konum Ayarları Yapılıyor",
"t56":"Dil Ayarları Yapılıyor",
"t57":"Host Ayarları Yapılıyor",
"t58":"Klavye Ayarları Yapılıyor",
"t59":"Live Kullanıcı Siliniyor",
"t60":"Sudoers Ayarları Yapılıyor",
"t61":"Initciop Oluşturuluyor",
"t62":"Kullanıcılar Ekleniyor",
"t63":"Lightdm Ayarları Yapılıyor",
"t64":"Grub Ayarları Yapılıyor",
"t65":"Diskler Çözülüyor",
"t66":"Kurulum Tamamlandı"
}

ingilizce = {"t1":"Milis Installation Tool",
"t2":"Back",
"t3":"Next",
"t4":"""    Milis Linux (National Operating System) is a standalone native Linux operating system project with its own package manager, produced from zero source code. As a general philosophy, it aims to facilitate Linux for the computer users in our country and to make the Milis Operating System a trouble-free operating system and to recover from software dependency. It is also a Turkish open source project for those who want to make any contribution.""",
"t5":"Documents",
"t6":"Forum",
"t7":"Git",
"t8":"Contact",
"t9":"Select language",
"t10":"Welcome to Milis Linux Installation",
"t11":"Keyboard Settings",
"t12":"Model",
"t13":"Country",
"t14":"Type",
"t15":"Location Settings",
"t16":"Zone",
"t17":"City",
"t18":"User Settings",
"t19":"User Name",
"t20":"Login Name",
"t21":"Computer Name",
"t22":"Mint 3 characters",
"t23":"Min 4 characters and letters",
"t24":"User Password",
"t25":"Min 6 characters and the passwords must be the same",
"t26":"Log in automatically without requiring password",
"t27":"Use same password for administrator account",
"t28":"Admin Password",
"t29":"Disk Settings",
"t30":"<b> 1-System partition: </b> This is the partition where the Militia will copy its systems. It is formatted in Ext4 format. <u>MUST NOT.</u>\n<b> 2-Swap partition: </b> Militia needs a disk partition to temporarily copy files when there is a ram shortage. If your computers RAM is low, create a swap partition. <u>OPTIONAL</u> \n<b> 3-UEFI partition: </b> If you have a BIOS with UEFI and want to use UEFI, you need an EFI space on the disk. If you have an existing operating system and the EFI domain it uses, please select it. If there are no other operating systems on your disk and you want to use UEFI, please create an EFI space. <u>OPTIONAL</u>",
"t31":"Disks",
"t32":"Refresh",
"t33":"System Partition",
"t34":"Swap Partition",
"t35":"UEFI Partition",
"t36":"Edit",
"t37":"Install grub loader",
"t38":"Not install grub loader",
"t39":"Installation Information",
"t40":"System Language",
"t41":"Keyboard Model",
"t42":"Keyboard Layout",
"t43":"Keyboard Variant",
"t44":"Location",
"t45":"If you continue, Milis Linux will be installed on the disk you selected.",
"t46":"Continue",
"t47":"Cancel",
"t48":"Milis Linux Is Being Installed",
"t49":"Umount Disks From The System",
"t50":"Mount Disks From The System",
"t51":"Make Chroot",
"t52":"Calculating Files for Copy",
"t53":"Copying",
"t54":"Make Fstab",
"t55":"Setting Location",
"t56":"Setting Language",
"t57":"Setting Host",
"t58":"Setting Keyboard",
"t59":"Remove Live Users",
"t60":"Setting Sudoers",
"t61":"Make Initciop",
"t62":"Adding Users",
"t63":"Setting Lightdm",
"t64":"Setting Grub",
"t65":"Umount Disks",
"t66":"Installation Complete"
}


diller = {"Türkçe":turkce,"English":ingilizce}
