turkce ={"t1":"Milis Kurulum Aracı",
"t2":"Geri",
"t3":"İleri",
"t4":"""	Milis Linux (Milli İşletim Sistemi) sıfır kaynak koddan üretilen, kendine has paket yöneticisine sahip, bağımsız tabanlı yerli linux işletim sistemi projesidir. Genel felsefe olarak ülkemizdeki bilgisayar kullanıcıları için linuxu kolaylaştırıp Milis İşletim Sisteminin sorunsuz bir işletim sistemi olmasını sağlamayı ve yazılımsal olarak dışa bağımlı olmaktan kurtarmayı esas alır. Ayrıca her türlü katkıda bulunmak isteyenler için bulunmaz bir Türkçe açık kaynak projesidir.""",
"t5":"Belgeler",
"t6":"Forum",
"t7":"Git",
"t8":"İletişim",
"t9":"Dil seçiniz",
"t10":"Milis Linux Kurulumuna Hoşgeldiniz",
"t11":"Klavye Ayarları",
"t12":"Model",
"t13":"Ülke",
"t14":"Tür",
"t15":"Konum Ayarları",
"t16":"Bölge",
"t17":"Şehir",
"t18":"Kullanıcı Ayarları",
"t19":"Kullanıcı Adı",
"t20":"Giriş Adı",
"t21":"Bilgisayar Adı",
"t22":"En az 3 karakterden oluşmalı",
"t23":"En az 4 karakter ve harflerden oluşmalı",
"t24":"Kullanıcı Şifresi",
"t25":"En az 6 karakterden oluşmalı ve şifreler aynı olmalı",
"t26":"Şifre istemeden otomatik giriş yap",
"t27":"Yönetici hesabı için aynı şifreyi kullan",
"t28":"Yönetici Şifresi",
}

ingilizce = {"t1":"Milis Installation Tool",
"t2":"Back",
"t3":"Next",
"t4":"""    Milis Linux (National Operating System) is a standalone native Linux operating system project with its own package manager, produced from zero source code. As a general philosophy, it aims to facilitate Linux for the computer users in our country and to make the Milis Operating System a trouble-free operating system and to recover from software dependency. It is also a Turkish open source project for those who want to make any contribution.""",
"t5":"Documents",
"t6":"Forum",
"t7":"Git",
"t8":"Contact",
"t9":"Select language",
"t10":"Welcome to Milis Linux Installation",
"t11":"Keyboard Settings",
"t12":"Model",
"t13":"Country",
"t14":"Type",
"t15":"Location Settings",
"t16":"Zone",
"t17":"City",
"t18":"User Settings",
"t19":"User Name",
"t20":"Login Name",
"t21":"Computer Name",
"t22":"Mint 3 characters",
"t23":"Min 4 characters and letters",
"t24":"User Password",
"t25":"Min 6 characters and the passwords must be the same",
"t26":"Log in automatically without requiring password",
"t27":"Use same password for administrator account",
"t28":"Admin Password"
}


diller = {"Türkçe":turkce,"English":ingilizce}
